// <auto-generated />
using System;
using InscricaoAula.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InscricaoAula.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024210041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("InscricaoAula.Models.AulaColetiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxVagas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("InscricaoAula.Models.Inscricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AulaColetivaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailParticipante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeParticipante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AulaColetivaId", "EmailParticipante")
                        .IsUnique();

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("InscricaoAula.Models.Inscricao", b =>
                {
                    b.HasOne("InscricaoAula.Models.AulaColetiva", "Aula")
                        .WithMany("Inscricoes")
                        .HasForeignKey("AulaColetivaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("InscricaoAula.Models.AulaColetiva", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
